apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iyo12v1py-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iyo12v1py-go 
  name: iyo12v1py-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: iyo12v1py-go 
